config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"

  resource :users, only: %i(create new)
  resource :sessions, only: %i(create new destroy)
  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews

  validates :name, :description, :price_in_cents, presence: {message: "Please fill in the %{attribute}"}
  validates :price_in_cents, numericality: true

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :review, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  # with has_secure_password, the following validations are added automatically: password must be present on creation, password length should be <= 72 characters, and confirmation of password (using a password_confirmation attribute)

  # NOTE: has_secure_password and validates are methods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method(:current_user)

  def current_user
    session[:user_id] && User.find(session[:user_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # Preloading the find_product method (at the bottom) for ONLY the following methods:
  before_action :find_product, only: [:edit, :show, :update, :destroy]
  before_action :new_product, only: [:create, :new]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new

    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]

    if @product.save
      flash[:notice] = "Product has been successfully created."
      redirect_to product_path(@product)
    else
      render :new
    end

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update

    @product = Product.find(params[:id])

    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]

    if @product.save
      flash[:notice] = "Product has been successfully updated."
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy

    if @product.destroy
      flash[:notice] = "Product has been successfully deleted."
      redirect_to products_path
      flash[:notice] = "You have deleted the product #{product.name}."
    else
      render :show
    end

  end

  def find_product
    @product = Product.find(params[:id])
  end

  def new_product
    @product = Product.new
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
      @review = Review.new
      @review.review = params[:review][:comment]
      @review.product_id = params[:product_id]

      if @review.save
        flash[:notice] = "Review has been successfully created."
        redirect_to @product
      end
    end

    def edit
      @review = Review.find_by(params[:id])
      @product = Product.find_by(params[:product_id])
    end

    def update
      @review.review = params[:review][:comment]
      @review.product = @product

      if @review.save
        flash[:notice] = "Review has been successfully updated."
        redirect_to @product
      else
        render :edit
      end
    end

    def destroy
      if @review.destroy
        flash[:notice] = "Review has been successfully deleted."
        redirect_to product_path(params[:product_id])
      else
        render :show
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    u = User.find_by(email: params[:session][:email])

    if u && u.authenticate(params[:session][:password])

      # Put the wristband on the User
      session[:user_id] = u.id
      redirect_to root_url
    else
      flash.now[:alert] = ["Login failsed, name and/or password are incorrect"]
      render :new
    end

  end

  def destroy
    # take off the wristband
    session[:user_id] = nil

    redirect_to root_url
  end
end

# There are three magic hashes available to you in a Rails Controller

# params
# session
# flash

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    # blank user
  end

  def create
    @user = User.new

    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "You have successfully sign up!"
      # Use _url in controllers
      redirect_to root_url
    else
      flash.now[:alert] = @user.errrors.full_messages
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Rainforest</h1>
      <%= link_to "Home", root_url %>
    </header>


<% if current_user %>
  <p>
    <%= link_to("Add a Product", new_product_path) %> |
    <%= link_to "Logout", sessions_path, method: :delete %>
  </p>

    <p>Hello <%= current_user.email %></p>

    <% else %>
      <%= link_to("New User", new_users_path)%>
      <%= link_to("Login", new_sessions_path)%>
<% end %>

    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/products/_product_form.html.erb
<%= form_for @product do |f| %>
  <div class="field">
    <p><%= f.label :name %></p>
    <p><%= f.text_field :name %></p>
  </div>

  <div class="field">
    <p><%= f.label :description %></p>
    <p><%= f.text_area :description %></p>
  </div>

  <div class="field">
    <p><%= f.label :price_in_cents, 'Price' %></p>
    <p><%= f.text_field :price_in_cents %></p>
  </div>
  <div class="field">
    <p><%= f.submit %></p>
  </div>
  <% if @product.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %>
      prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'product_form', product: @product %>

app/views/products/index.html.erb
<h1>Products#index</h1>

<p>All our products are listed here</p>

<ul>
<% @products.each do |product| %>
    <h2><%= product.name%></h2>
    <h3>Description</h3>
    <p><%= product.description %></p>
    <p>Price: <%= product.price_in_dollars %></p>
    <p><%= link_to "View Details", product_path(product)%> </p>
<% end %>
</ul>

app/views/products/new.html.erb
<h1>Products#new</h1>

<p><%=link_to "Back",products_path %></p>

<h1>Add a New Product</h1>
<%= render 'product_form', product: @product %>

app/views/products/show.html.erb
<h1>Products#show</h1>

<h1><%= @product.name %></h1>
<p><%= link_to "Edit Product", edit_product_path(@product) %> | <%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure you want to delete this product?" } %> </p>
<h3>Description</h3>
<p><%= @product.description %></p>
<p>Price: <%= @product.price_in_dollars %></p>
<br>

<h1>Review</h1>

<ul>
  <% @product.reviews.each do |review| %>
    <li>
      <p><%= review.review %></p>
      <p>Posted on: <%= review.created_at %></p>
      <p><%= link_to "Edit Review", edit_product_review_path(@product, review)%> | <%= link_to "Delete", product_review_path(@product, review), method: :delete, data: {confirm: "Are you sure you want to delete this review?" } %> </p>
    </li>
    <% end %>
</ul>

<h2>Product Reviews</h2>
<%= render '/reviews/reviews', review: @review %>


<h4>New Review</h4>
<%= render '/reviews/form', review: @review %>

<p><%= link_to "Back", products_path%></p>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :review %><br />
    <%= f.text_area :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_reviews.html.erb
<ul>
  <% @product.reviews.each do |review| %>
    <li>
      <p><%= review.review %></p>
      <p>Posted on: <%= review.created_at %></p>
      <p><%= link_to "Edit Review", edit_product_review_path(@product, review)%> | <%= link_to "Delete", product_review_path(@product, review), method: :delete, data: {confirm: "Are you sure you want to delete this review?" } %> </p>
    </li>
    <% end %>
</ul>

app/views/reviews/edit.html.erb
<h1> Editing a Review </h1>

   <%= render 'form', review: @review %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <ul>

    <% @user.errors.full_messages.each do |m| %>
    <li> <%= m %> </li>
    <% end %>

  </ul>
<% end %>

<%= form_for (@user) do |f| %>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "Sign Up" %>

<% end %>